image: instantsolutions/gitlab-ci-android-runner:latest

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p $GRADLE_USER_HOME
    - chmod +x ./gradlew

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

stages:
  - build

build:
  stage: build
  script:
    - echo "build"
